[package]
name = "ios_beta_notifications"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
feed-rs = "1.0"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
serde_json = "1.0"
dotenv = "0.15"
